### ISSUE TITLE
Save etymological data

### ISSUE THREAD

**Issue by xome4ok** [componavt/wikokit#15]
As I can tell for now, everything from wiktionary's "etymology" section is being ignored. 
I couldn't find it anywhere in the db, neither could I find any indications in papers from readme of this data being stored.
Could you please add feature for saving etymological data or if it is already stored, point me where I can find it?

**Comment by componavt** [comment]
To my regret, the etymology section at this moment do not parsed at all :(
Sorry, now I have no plans to parse the Etymology section in Russian Wiktionary. 

You are welcome to fork this project :)

**Comment by xome4ok** [comment]
I think I'll do, if there're no other alternatives.

Anyway, thanks for answer :)
